### ISSUE TITLE
vesta modules error with webtrees 2.0.3-dev

### ISSUE THREAD

**Issue by jpretired** [vesta-webtrees-2-custom-modules/vesta_common#1]
With last webtrees version 2.0.3-dev there is an error in vesta modules:
`Fatal error: Class Vesta\VestaCommonLibModule contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Fisharebest\Webtrees\Module\ModuleCustomInterface::customModuleLatestVersion) in /var/www/Projekty/webtrees-2/modules_v4/vesta_common/VestaCommonLibModule.php on line 9 `

**Comment by ric2016** [comment]
Will probably not be fixed until the next webtrees release - there are further issues in the 2.0.3-dev code which have to be addressed in order to keep all Vesta modules working.

In general, releases should not be expected to work with dev versions, at least as long as there are ongoing changes of important webtrees core code. This may settle down a bit in the future.

**Comment by ric2016** [comment]
Fixed in latest release.
